name: csep-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - scipy
  - matplotlib<=3.5.3
  - pyproj
  - obspy
  - python-dateutil
  - pytest
  - cartopy
  - shapely
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - pillow
  - vcrpy
  - mercantile

