name: csep-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - scipy
  - h5py
  - matplotlib
  - pyproj
  - obspy
  - python-dateutil
  - cartopy
  - shapely
  - mercantile

