# Time Constants
import numpy

SECONDS_PER_ASTRONOMICAL_YEAR = 31557600
SECONDS_PER_DAY = 60*60*24
SECONDS_PER_HOUR = 60*60
SECONDS_PER_WEEK = SECONDS_PER_DAY*7
SECONDS_PER_MONTH = SECONDS_PER_WEEK*4
DAYS_PER_ASTRONOMICAL_YEAR = 365.25

MW_5_EQS_PER_YEAR = 10

# Magnitude Bins
min_mw = 2.5
max_mw = 8.95
dmw = 0.1
CSEP_MW_BINS = numpy.arange(min_mw, max_mw+dmw/2, dmw)
