name: Build and upload to PyPI

# Only build on tagged releases
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and upload sdist
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          generate-run-shell: true
          environment-file: requirements.yml
          create-args: >-
            python=3.10

      - name: Check dependencies
        run: |
          conda info -a
          conda list

      - name: Create sdist
        run: |
          python setup.py check
          python setup.py sdist

      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_upload_token }}